version: "3.5"

services:
  vue:
    build: ./frontend
    volumes:
      - ./frontend:/usr/app/
      - /usr/app/node_modules
    ports:
      - ${COMPOSE_FRONTEND_PORT}:3000

  # Express Service
  express:
    build: ./backend
    volumes:
      - ./backend:/usr/app/
      - /usr/app/node_modules
    ports:
      - ${COMPOSE_BACKEND_PORT}:8000

  # Mongo Service
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"

  # Mongo Admin Panel
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
