version: "3.5"

services:
  # Express Service
  express:
    build: .
    command: yarn dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mongo

  # Mongo Service
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"

  # Mongo Admin Panel
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
